{{- if .Values.clusterIssuer.production.create -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $.Values.clusterIssuer.production.name }}
  labels:
    app: {{ include "cert-manager-duckdns-webhook.name" . }}
    chart: {{ include "cert-manager-duckdns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
    email: {{ $.Values.clusterIssuer.email }}
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: {{ include "cert-manager-duckdns-webhook.fullname" . }}-production
    server: {{ $.Values.clusterIssuer.production.server }}
    solvers:
      - dns01:
          webhook:
            config:
              apiTokenSecretRef:
                key: token
                name: {{ include "cert-manager-duckdns-webhook.secretName" . }}
            groupName: {{ .Values.groupName }}
            solverName: duckdns
{{- end -}}